directory: /data/tank/music/flac
library: /data/tank/music/library.db
plugins: embedart fetchart ftintitle mbsync convert mbsubmit lastgenre

lastgenre:
  auto: yes
  canonical: no
  count: 1
  force: yes
  min_weight: 10
  prefer_specific: no
  source: album
  separator: ", "
  whitelist: yes
  title_case: yes

musicbrainz:
  extra_tags: [country, label]

paths:
  default: $albumartist/$album%aunique{}/$track $title
  singleton: Non-Album/$artist/$title
  comp: Compilations/$album%aunique{}/$track $title

original_date: true

convert:
  dest: /data/tank/music/mp3/
  format: v0
  never_convert_lossy_files: yes
  formats:
    v0:
      command: /usr/home/ajm/scripts/convert-to-mp3.sh v0 "$source" "$dest"
      extension: mp3
