directory: /mypool/tank/music/flac
library: /mypool/tank/music/library.db
plugins: embedart fetchart ftintitle zero mbsync convert mbsubmit

musicbrainz:
  extra_tags: [country, label]

paths:
  default: $albumartist/$album%aunique{}/$track $title
  singleton: Non-Album/$artist/$title
  comp: Compilations/$album%aunique{}/$track $title

original_date: true

zero:
  fields: genre
  update_database: true

convert:
  dest: /mypool/tank/music/mp3/
  format: v0
  never_convert_lossy_files: yes
  formats:
    v0:
      command: /usr/home/ajm/scripts/convert-to-mp3.sh v0 "$source" "$dest"
      extension: mp3
    cbr320:
      command: /usr/home/ajm/scripts/convert-to-mp3.sh 320 "$source" "$dest"
      extension: mp3

