#!/bin/sh
#
# PROVIDE: blocky
# REQUIRE: networking
# KEYWORD:

. /etc/rc.subr

name="blocky"
rcvar="blocky_enable"
blocky_command="/home/ajm/go/bin/blocky --config /data/tank/blocky/config.yaml"
pidfile="/var/run/blocky/${name}.pid"
command="/usr/sbin/daemon"
command_args="-P ${pidfile} -r -f ${blocky_command}"

load_rc_config $name
: ${blocky_enable:=no}

run_rc_command "$1"

