#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Andrew Monks"
email = "a@monks.co"

[ui]
merge-editor = ":builtin"
editor = "nvim"
pager = "ov --exit-write"
default-command = "log"

[git]
private-commits = "description(glob:'DO NOT MERGE:*') | description(glob:'DO-NOT-MERGE:*')"

